name: cicd
on:
  workflow_dispatch:
jobs:
  common:
    uses: venkat-actions/reusable-workflows/.github/workflows/common.yaml@main
    with:
      project: roboshop
      component: catalogue 
      app_type: nodejs